version: '3.8'  # Docker Compose Version

services:
  web:
    build: .  # Verzeichnis mit dem Dockerfile
    ports:
      - "5000:5000"  # Zugriff auf die Web-App
    volumes:
      - ./downloads:/app/downloads  # Verzeichnis für heruntergeladene Dateien
      - ./logs:/app/logs  # Verzeichnis für Logs
    depends_on:
      - mongodb  # MongoDB-Service muss vor dem Web-Service starten
    networks:
      - scraper-network
    restart: unless-stopped  # Automatisch neustarten, wenn der Container stoppt
    env_file:
      - docker/config/development.env

  mongodb:
    image: mongo:latest  # Offizielles MongoDB-Image
    ports:
      - "27017:27017"  # Zugriff auf MongoDB
    volumes:
      - mongodb_data:/data/db  # Persistente Speicherung der MongoDB-Daten
    env_file:
      - docker/config/development.env  # Umgebungsvariablen für MongoDB
    networks:
      - scraper-network
    restart: unless-stopped

volumes:
  mongodb_data:  # Definiertes Volume für MongoDB-Daten

networks:
  scraper-network:  # Netzwerk für die Services
    driver: bridge
